# Generated by Django 2.2.6 on 2019-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crone_job', '0002_auto_20191008_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='cron',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='general_answer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='notification_deactivate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='notification_error',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='notification_jobs',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
