# Generated by Django 2.2.6 on 2019-10-11 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crone_job', '0004_cronjob_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
