# Generated by Django 2.2.6 on 2019-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crone_job', '0005_auto_20191011_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
